name: "mydealzCustomRSS"
description: "Generate Custom RSS Feeds for mydealz"
version: "0.1.0"
slug: "mydealzCustomRSS"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  dealtemp: 200
schema:
  dealtemp: int
